stages:
- name: Render and Publish Helm Charts
  steps:
  - runScriptConfig:
      image: jgreat/rancher-pipeline-publish-chart:0.0.2
      shellScript: publish-chart.sh
    env:
      HELM_REPO_URL: https://vote-demo-charts.eng.rancher.space/vote-demo-web/
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: HELM_REPO_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: HELM_REPO_USERNAME
timeout: 10
notification: {}
